[package]
name = "wavry-media"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = "0.11"
gstreamer = "0.22"
gstreamer-app = "0.22"
gstreamer-video = "0.22"
