[package]
name = "rift-core"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bitflags.workspace = true
serde.workspace = true
thiserror.workspace = true
